dataset_path: Helsinki-NLP/opus-100
dataset_name: en-fa
source_language: en
target_language: fa
max_seq_len: 128
source_file_path: outputs/source_tokenizer.json
target_file_path: outputs/target_tokenizer.json
train_batch_size: 12
val_batch_size: 1
d_model: 512
num_heads: 8
n_encoder: 10
n_decoder: 10
dropout: 0.1
num_epochs: 1
lr: 0.0001
weight_decay: 0.01